### ISSUE TITLE
Incorporate various bug fixes from @thewtex

### ISSUE THREAD

**Issue by Besler** [Besler/ITKBoneEnhancement#8]
You can find these fixes at https://github.com/Besler/ITK-KrcahSheetnessImageFilter/compare/master...thewtex:module

**Comment by Besler** [comment]
I am going to wait until the next version of ITK is released with GoogleTest so I can write the tests in a more standard fashion.

Commits that should be incorporated:
https://github.com/Besler/ITK-KrcahSheetnessImageFilter/commit/6ed179377ad91b15ba795a9e0a7e5d68fd1d88c5
https://github.com/Besler/ITK-KrcahSheetnessImageFilter/commit/fca2497a82c0015cbe12cb95be1b48a349f31219

Most others have been incorporated already.

**Comment by thewtex** [comment]
:+1:
