### ISSUE TITLE
Double check the request region for MultiScaleHessianEnhancementImageFilter

### ISSUE THREAD

**Issue by Besler** [Besler/ITKBoneEnhancement#9]
Be certain that the requested region for MultiScaleHessianEnhancementImageFilter is correct for the various filters it composes. Currently, the parameter estimation filters all require the largest possible region. MultiScaleHessianEnhancementImageFilter should do the same then too.

**Comment by Besler** [comment]
Currently, `MultiScaleHessianEnhancementImageFilter` requests the largest possible region and prevents streaming. Internally, we use `HessianRecursiveGaussianImageFilter` which also requests the largest possible region. This means we cannot use the `StreamingImageFilter` at the end of pipeline for a memory efficient implementation. I believe this is because `HessianRecursiveGaussianImageFilter` uses an IIR implementation for the derivatives and cross derivatives of the Gaussian filters.

This has been discussed in the mail list a few times:
https://public.kitware.com/pipermail/insight-users/2011-March/040421.html
http://itk-users.7.n7.nabble.com/itkSymmetricEigenAnalysisImageFilter-td9870.html
http://itk-users.7.n7.nabble.com/ITK-users-How-to-Calculate-Hessian-Matrix-from-Gradient-Image-td35400.html

To correct this, two courses of action are needed:
1) Implement `HessianRecursiveGaussianImageFilter` using FIR filters enabling streaming.
2) Reimplement all `*ParameterEstimation` filters to estimate parameters using subregions instead of requesting the whole image.

@thewtex @araex Any thoughts?

Note: Discussion started on PR https://github.com/Besler/ITKBoneEnhancement/pull/5

**Comment by thewtex** [comment]
@Besler Yes, good ideas. +1 to 1.). Regarding 2.), yes -- in practice, only a sufficiently large `RequestedRegion` is likely needed for parameter estimation, and using the entire image for very large images could be overkill anyway.

**Comment by Besler** [comment]
Yes, good point. These filters are specific to CT and bone. Practically, we could restrict the `RequestedRegion` to where there is bone with a threshold somewhere between 200 and 600 HU. I will think more about the implementation here.

**Comment by Besler** [comment]
Update on Gaussian implementations. We want to include streaming to allow implementation on small machines.

**Theory**
For those interested in theory, the paper ["Recursive Gaussian filters" by Dave Hale](http://www.cwp.mines.edu/Meetings/Project06/cwp546.pdf) is a good read. Also, (Tony Lindeberg's thesis "Discrete Scale-Space Theory and the Scale-Space Primal Sketch")[http://www.diva-portal.org/smash/get/diva2:473362/FULLTEXT01.pdf] is full of implementation details.

In general, the run time of FIR filters scale in polynomial time with the standard deviation of the kernel. IIR do not because they rely on a recursion equation. However, FIR filters are streamable. IIR filters are not streamable. The trade off is time vs memory.

**HessianRecursiveGaussianImageFilter**
The closest streamable implementation to `HessianRecursiveGaussianImageFilter` is `HessianRecursiveGaussianImageFilter`. This filter evaluates the Hessian at an index in the image and is not an `ImageToImage` filter.

**RecursiveGaussianImageFilter**
Internally, `HessianRecursiveGaussianImageFilter` uses `RecursiveGaussianImageFilter` to compute the convolution with a second order derivatives of a Gaussian. `DiscreteGaussianImageFilter ` is the FIR equivalent to `RecursiveGaussianImageFilter` but does not compute the derivatives. `DiscreteGaussianDerivativeImageFilter` computes the derivatives using a FIR implementation.

**Problem**
We can implement a streamable Hessian filter. However, parameter estimation requires computing a scalar over the hessian of all voxels. Definitionally, this is not streamable. We have a few ways to get around this:
- **Process twice.** That is, do parameter estimation by streaming each region. Then, stream again to implement the enhancement function.
- **Sampling.** Sample the image and estimate the parameters over this sampling. The sampling can be done with a mask as well.
- **Streaming all the way.** Just stream the filters together and use separate parameters for each stream. The filter will not be consistent at the border between two regions.
- **Single Region estimation**. Do parameter estimation with a single candidate region, apply those parameters to all streamed regions.

@ypauchard @araex @thewtex I'll give this some more thought. I think this is a design problem. Let me know if you have any ideas about implementing the `*ParameterEstimation` filters with streaming.

**Comment by thewtex** [comment]
Excellent, summary @Besler !

Another possible approach is to have `itk::KrcahEigenToScalarParameterEstimationImageFilter` inherit from [`itk::StreamingImageFilter`](https://itk.org/Doxygen/html/classitk_1_1StreamingImageFilter.html). We just may need to add a check [here](https://github.com/InsightSoftwareConsortium/ITK/blob/6883e0007ee69e0c8fd9afde79c56fa052e699d7/Modules/Core/Common/include/itkStreamingImageFilter.hxx#L202-L204) so that the copy is only performed when `inputPtr != outputPtr`.

**Comment by Besler** [comment]
I finally get it. `itk::StreamingImageFilter` is a very beautiful solution. `itk::MultiScaleHessianEnhancementImageFilter` won't be streamable, but this will greatly reduce memory demands by not instantiating the entire Hessian image at once. By streaming, the filter will create the entire eigen image in regions. Very roughly, the filters will now require 4x the memory of your original image instead of 10x (I think...) That's a 2.5x improvement!

So here is the new plan:
- Create `itk::HessianGaussianImageFilter` which is an FIR, streamable implementation of `itk:: HessianRecursiveGaussianImageFilter`
- `*ParameterEstimation` filters inherit from `itk::StreamingImageFilter`. Override the method `UpdateOutputData`
- `itk::MultiScaleHessianEnhancementImageFilter` still not streamable but less memory intensive.

The only other option is to have a method like `SetEstimationRegion(RegionType estimationRegion)` where `*ParameterEstimation` only computes parameters over the given region. This region would typically be taken as the center of the largest region shrunk by some factor. Then `MultiScaleHessianEnhancementImageFilter` can produce an image up to `RequestedReqion.Crop(estimationRegion)`.

**Comment by thewtex** [comment]
:+1: Great plan!
